[package]
name = "bevy_coordinate_systems"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"

[dev-dependencies]
bevy_basic_camera = { git = "https://github.com/DGriffin91/bevy_basic_camera" }

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
